title = "Farahnoz Melieva | MS in Computer Science · ML Researcher · Software Engineer"
base_url = "https://farahnoz.github.io/"
compile_sass = false
build_search_index = false

taxonomies = [
    {name = "tags"},
]

[extra]
author = "Farahnoz Melieva"
